-- Import All Clubs from clubs.js into Supabase
-- Run this AFTER running simple-schema.sql
-- This will insert all 52 clubs/organizations into the organizations table

-- Function to escape single quotes for SQL
-- We'll use PostgreSQL's dollar-quoting or escape manually

INSERT INTO organizations (name, description, category, website, email, image) VALUES
('AlgoGators Investment Fund', 'AlgoGators Investment Fund, Inc. is a student-led, quantitative hedge fund that develops and deploys algorithmic trading strategies into derivative markets globally. Our team is made up of ~30 members with a wide variety of backgrounds and manages $500k in AUM. We''re on a mission to democratize quantitative finance. We do this by providing a platform for undergraduate students to gain hands-on experience in building systematic trading systems and managing live capital. Applications are welcomed at the commencement of each semester. To find out more, please visit our website below.', ARRAY['Investment Funds', 'Finance'], 'https://algogators.com/', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQH07Uuy-AjrzA/company-logo_200_200/company-logo_200_200/0/1710348448068?e=1764806400&v=beta&t=JHN8BjFjgOE4FcodUWw8WYPfXEESkdZQ6oLCoBV1gBU'),
('Association of Latino Professionals for America', 'ALPFA creates opportunities, adds value, builds relationships for its members, the community and its business partners while expanding Latinx leadership in the global workforce.', ARRAY['General Business', 'Diversity'], 'https://www.ufhsa.com/association-of-latino-professionals', 'hsapresidentuf@gmail.com', 'https://media.licdn.com/dms/image/v2/C4D0BAQHkYLm3edgFAQ/company-logo_200_200/company-logo_200_200/0/1676684911688/alpfa_uf_logo?e=1764201600&v=beta&t=rmCPvcL89dfXqfkucHSWIlVfqUS8k8atHJg_4fCKQn4'),
('American Marketing Association', 'As a premier and professional organization within the prestigious Warrington College of Business, the University of Florida Collegiate Chapter of the American Marketing Association prides itself on the personal and professional development of its members. We strive to bridge the gap between classroom instruction and real-world business experience, by providing a medium for students to interact with professionals in the industry, develop tangible marketing skills, and engage with like-minded individuals in a creative atmosphere.', ARRAY['Marketing', 'Professional Development'], 'https://www.amagator.com/', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQEE59_NtzGZhg/company-logo_200_200/B4EZeDkhFlG4AQ-/0/1750259078276/american_marketing_association_university_of_florida_chapter_logo?e=1764806400&v=beta&t=uxtPj4Y1NmC7pL1tKktjjSz89Q58e36VmSyym99NSPg'),
('Asian Business Student Association', 'The Asian Business Student Association is an Asian-interest, but not Asian-exclusive, business organization that provides students with a community and tools to succeed at the University of Florida and beyond. Our mission is to empower and develop students professionally and personally in a supportive, and safe environment through networking, mentorship, public service, cultural involvement, and more!', ARRAY['General Business', 'Diversity'], 'https://l.instagram.com/?u=https%3A%2F%2Flinktr.ee%2Fufabsa%3Ffbclid%3DPAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGndp3LdHFxQpxH0vld60DZuL3bUD-BAUcB5zK38uxXPuz5W4_L5bIBkEPZeQA_aem_ok1nFJGORsBNx4UyBk0fdg&e=AT0EFUDw-2TdUqdcLdSTCliYS1BlkHqlEEGs4LhHZ9ImF8SJ5sLrC6Be1FdY45j-aQgqresLMMmTuRDXJO9hMEZrAtFUIIJSBNKpfHwvRA', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQECyFe3enBNdA/company-logo_200_200/company-logo_200_200/0/1684350506375/ufabsa_logo?e=1764201600&v=beta&t=em_ZOXhJiGVBeyqnaY-dxe1zlAEfmMs4OA3AsrEW-cU'),
('Beta Alpha Psi', 'Beta Alpha Psi is an esteemed, national honor society for students and professionals in financial information fields. Our primary objective is to encourage and recognize scholastic and professional excellence in accounting, finance, and information systems. We promote the study and practice of these disciplines, offering members opportunities for self-development, service, and networking with practicing professionals. We also foster a strong sense of ethical, social, and public responsibility. With 115 chapters nationwide, Beta Alpha Psi continues to uphold its legacy of excellence. The Upsilon Chapter at the University of Florida, founded in 1938, was the 18th chapter established, contributing to this proud tradition.', ARRAY['Honor Society', 'Accounting', 'Finance'], 'https://www.linkedin.com/company/beta-alpha-psi-upsilon-uf/', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQHBYgrm0WAmhw/company-logo_200_200/company-logo_200_200/0/1714961291500?e=1764201600&v=beta&t=pYkE5ZSHofCC5UMo5XTJqoty_rZJonnP6Zi9MuY-2uI'),
('Black Students in Business', 'Black Students in Business serves to establish a community of excellent Black students within the Warrington College of Business at the University of Florida. This organization will host numerous professional and social events curated specifically for the enrichment of our Black business community.', ARRAY['General Business', 'Diversity'], 'l.instagram.com/?u=https%3A%2F%2Flinktr.ee%2Fufbsib%3Ffbclid%3DPAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnkuEO-Z1nGmYOQjVYySbYvhDngVU9CWsWjgtZDSXGHgCCVxOSFrlwPEgzEwo_aem_DLedCa6UVK94DC3gXrjMvg&e=AT2_47d9u63xofpcZ-Uy2Y32BjubH1s5_h4h6FcvGYE2sZzWe9V0zQu2uozDYC1k7ixbPCqjoK3OuOLxHJ-idqRnRp7jA4MC3CWa7ZZBiA', NULL, 'https://media.licdn.com/dms/image/v2/C4E0BAQF0l1Zntrp2MA/company-logo_200_200/company-logo_200_200/0/1630620736445?e=1764806400&v=beta&t=5_oeG_D5380OJTFGisQRDs4xaEXEVN16IZ1udB6KkVw'),
('Business Law Society', 'The primary purpose of Business Law Society is to expose students to the wide range of career paths within business law while also offering community service outreach programs related to the field. Career path exposure includes bringing in speakers with experience in both business and law to provide career advice, share their personal journeys, and offer networking opportunities. This exposure is further enhanced through case studies and educational sessions on various career paths within the field. Our community service outreach includes training students to become VITA (Volunteer Income Tax Assistance) certified, helping underprivileged communities with tax filing, and offering personal finance education to high schools and community groups, empowering individuals with essential financial literacy skills.', ARRAY['General Business', 'Professional Development'], 'https://www.businesslawsocietyuf.org/', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQEvcteD21tyWQ/company-logo_200_200/company-logo_200_200/0/1724716253218?e=1764806400&v=beta&t=SsU9E6uLCHvrSw-2-2uJebxQVcjC6iyUltJnhXijUgs'),
('Business Undergraduate Mentorship Program (BUMP)', 'The Business Undergraduate Mentorship Program (BUMP) pairs one freshman, sophomore, or transfer student with a student leader that possesses a variety of experiences and knowledge in how to excel within the business school and beyond. BUMP includes developmental meetings as well as networking opportunities for both mentees and mentors through socials and AlumNights​. With access to a personal mentor, a network of 140+ mentors and mentees, and a large network of successful alumni, BUMP is sure to impact your college career for the better.', ARRAY['Program', 'Professional Development'], 'https://warrington.ufl.edu/current-students/undergraduate/business-undergraduate-mentorship-program/', NULL, 'https://media.licdn.com/dms/image/v2/C4E0BAQH0fTGyv5DR6A/company-logo_200_200/company-logo_200_200/0/1630590971114/uf_business_undergraduate_mentorship_program_logo?e=1764806400&v=beta&t=JIbyDb0m5I6FbUim6dVHGaNj5-ZT-p3hjtT2Vu9740M'),
('Leadership Development Program', 'The Leadership Development Program enables and inspires undergraduate students to grow personally and professionally, pursue involvement opportunities, and establish a network through mentorship and experiential learning. The program keeps students on track to have a well-rounded leadership experience and successful college career at the University of Florida.', ARRAY['Professional Development', 'Program'], 'https://warrington.ufl.edu/current-students/undergraduate/leadership-development-program/', NULL, 'https://media.licdn.com/dms/image/v2/C4E0BAQHxRAg62_NUJQ/company-logo_200_200/company-logo_200_200/0/1630575009354/leadership_development_program_uf_logo?e=1764806400&v=beta&t=uRfjCS8eeucnVkP4rEckLtinMWCSxOBrv5Fr2fdnGLM'),
('Caimanes Student Managed Equity Hedge Fund', 'Long/Short Equity Hedge Fund based at the University of Florida', ARRAY['Investment Funds', 'Finance'], 'https://warrington.ufl.edu/current-students/undergraduate/caimanes-equity-hedge-fund/', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQGqNyLOjzrylw/company-logo_200_200/B4EZjmdjC3GoAQ-/0/1756213162631/uf_caimanes_student_managed_equity_hedge_fund_logo?e=1764806400&v=beta&t=mw29KgvkdcUxPQIpndc3TrasjrZmxkGIkAyUYSKmZhU'),
('CHOMP Partners', 'CHOMP Partners is a student-run private equity firm that provides a unique learning experience for students interested in the field of private equity. The firm is open to all students, regardless of major, and provides a platform for students to learn about the financial industry and to develop their skills in the field. The firm is also a platform for students to network with professionals in the financial industry and to gain experience in the field.', ARRAY['Finance'], 'https://chomppartners.com', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQF_76tLiXuiRw/company-logo_200_200/B4EZbA7aTDGcAM-/0/1746993522730/chomp_partners_logo?e=1764806400&v=beta&t=ZjcH-Ke2VMnYVPgOJbbYywpDshFTQ6MBqv5ZazK8l4A'),
('Delta Sigma Pi', 'Delta Sigma Pi is a Professional Fraternity organized to foster the study of business in universities; to encourage scholarship, social activity, and the association of students for their mutual advancement by research and practice; to promote closer affiliation between the commercial world and students of commerce, and to further a higher standard of commercial ethics and culture and the civic and commercial welfare of the community.', ARRAY['General Business', 'Professional Development', 'Fraternity'], 'https://www.ufdsp.com/', NULL, 'https://media.licdn.com/dms/image/v2/C4E0BAQHd_UXgyj5_fQ/company-logo_200_200/company-logo_200_200/0/1630625671583?e=1764806400&v=beta&t=ulxSfSZjTXpZP9CpEIUI9oNxLgzxmsFAGwplypwMqkI'),
('DISS Capital', 'DISS Capital is a student investment fund that provides a unique learning experience for historically underrepresented students within finance to expose its members to careers in finance. DISS Capital aims to create a community for underrepresented students at universities that are not traditionally targeted with the tools and mentorship needed to ascend into these lucrative careers. We are a group of student leaders who want to demystify this process and forge a path for students of the future to follow.', ARRAY['Finance', 'Diversity'], 'https://disscapital.com/', NULL, 'https://media.licdn.com/dms/image/v2/C4E0BAQEFKBquoDHu_w/company-logo_200_200/company-logo_200_200/0/1680045716616/disscapital_logo?e=1764806400&v=beta&t=2X-s-Lm53Q2MX0eK5472Je9AoGFboRLGxiN84iiPY_Q'),
('Entrepreneurship Collective', 'At the Entrepreneurship Collective, we serve as a connecting point between creative problem solvers and the tools/resources necessary to create new businesses. We provide a home for students of all majors interested in learning more about the startup community through connecting members with the entrepreneurial community beyond the university. The Entrepreneurship Collective aims to serve the broad range of both graduate and undergraduate students at the University of Florida seeking to engage in the topics of entrepreneurship, creativity, and innovation in educative and social capacities by fostering a strong network of like-minded individuals in order to provide value to others in the Entrepreneurship Collective, the Gainesville Community and the world.', ARRAY['Entrepreneurship'], 'https://linktr.ee/EntrepreneurshipUF', 'entrepreneurshipuf@gmail.com', 'https://media.licdn.com/dms/image/v2/D4E0BAQE0K4p-Z7p9mw/company-logo_200_200/B4EZarmQE7GcAM-/0/1746635654159/eco_at_uf_logo?e=1764806400&v=beta&t=U5zBAJ1S5Ew9J_csYDK_RAPjgBOuv_Xlg2cdnx3A4Pc'),
('Entrepreneurship Through Acquisition Club', 'The Entrepreneurship Through Acquisition Club (ETA) is dedicated to fostering a community of students interested in the model of entrepreneurship through acquisition (ETA), i.e., acquiring and growing existing businesses rather than starting new ventures from scratch. The club aims to build awareness of ETA pathways as a viable form of entrepreneurship; Connect students with industry professionals, alumni, and community mentors experienced in acquisitions, search funds, and business turnarounds; Facilitate learning through workshops, speaker events, networking sessions, and student-led discussions focused on the skills and knowledge needed to evaluate, acquire, and scale an existing company; Encourage a supportive ecosystem wherein students can share resources, develop their networks, and collaborate on acquisition-related projects or initiatives', ARRAY['Entrepreneurship'], 'https://orgs.studentinvolvement.ufl.edu/Organization/entrepreneurship-through-acquisition-club', NULL, NULL),
('First-Generation Business Leaders', 'The purpose of FGBL is to create a supportive and inclusive environment among first-generation business students. We achieve this through mentorship programs, networking events, exposure to real-world business scenarios, and insights from professional guest speakers. Our ultimate goal is to nurture and develop the leaders of tomorrow, equipping them with the knowledge and skills they need to excel in their future careers. Through our regular meetings, outreach initiatives, and social events, we strive to build a strong community of first-generation business students who are ready to make their mark in the business world and their community.', ARRAY['General Business', 'Diversity', 'Professional Development'], 'https://linktr.ee/FGBL?utm_source=linktree_profile_share&ltsid=d4bd77ce-e1c2-4583-bd4e-00dfd71781cc', 'firstgenbusinessleaders@gmail.com', 'https://media.licdn.com/dms/image/v2/D4E0BAQFm5eztuyn2wQ/company-logo_200_200/B4EZYD3D9FHUAI-/0/1743821490490?e=1764806400&v=beta&t=X0hjEDp6B_r2D94LKS7H0qFtji_xtQOWH9jkPO6NIys'),
('Finance Professional Development', 'Welcome to the Finance Professional Development Program (FPD) at the Warrington College of Business, where we''re dedicated to shaping future finance leaders. Our program is split into 12 specialized tracks in diverse areas of the industry such as Asset Management, Investment Banking, FinTech, Consulting and more.Participation in an FPD track opens doors to experiential learning through weekly track meetings, workshops, technical training sessions, guest speakers, networking events, case competitions, conferences, site visits, and alumni involvement.', ARRAY['Program', 'Finance', 'Professional Development'], 'https://warrington.ufl.edu/current-students/undergraduate/finance-professional-development/', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQEuAw5eTCnIIw/company-logo_200_200/B4EZU.RIUiHcAI-/0/1740506433205/warrington_fpd_logo?e=1764806400&v=beta&t=73RTJwfFzMoNyKEFRuyi8vPJ4HorslR6raRbqJ48e4s'),
('Florida Business Leadership Society', 'The Florida Business Leadership Society is a professional development business organization at the University of Florida. We pride ourselves on our dedication, professionalism and service. Our mission is to provide all students with the appropriate business acumen and professional development necessary to represent themselves both within the University of Florida and as alumni in the professional realm. Florida Business Leadership Society strives to ensure business students make the most out of their time at University of Florida. As a student-run organization, you can bet that those involved in FBLS truly care about the club, because it''s completely voluntary work. From holding classes on how to prepare for an interview to weekend trips to Lake Wauberg, we''re dedicated to making sure our members understand professionalism while maintaining our sense of fun.', ARRAY['General Business', 'Professional Development'], 'https://fbls-uf.weebly.com/', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQHweDgAuOo9LA/company-logo_200_200/B4EZjrfbYPIUAM-/0/1756297541524/florida_business_leadership_society_fbls_logo?e=1764806400&v=beta&t=p-MY8r-cMo0yjlux2EIC2Y1MFexnUiH9eOqyrhHORRw'),
('Florida Cryptocurrency and Alternative Assets CLub', 'The Florida Cryptocurrency and Alternative Assets Club''s goal is to establish an organization that discusses cryptocurrencies, alternative assets, and their place in society. We want to educate students about cryptocurrency and provide an environment where people can discuss the market and factors that are having an impact on crypto and the economy. We believe crypto has a bright future and it is our desire to have discussions with our fellow UF students on a weekly basis. We are excited to note that we have verbal agreements from professional crypto day traders to be guest speakers at our weekly meetings. We will encourage students from all majors to join the club. We will make it a place where students of all majors, backgrounds, and financial expertise can share and learn. We believe our club has unlimited potential and will have a positive impact on the UF community. We are extremely enthusiastic about our idea, are dedicated to hitting the ground running and cannot wait to get started.', ARRAY['Technology', 'Finance'], 'https://www.instagram.com/ufcryptoclub/', NULL, 'https://media.licdn.com/dms/image/v2/C4E0BAQGFwaDcExUzUQ/company-logo_200_200/company-logo_200_200/0/1630967198138?e=1764806400&v=beta&t=m2Dqi9SL25spiweoBk3k1wMNcS1dzgIi5Hr8xsXnkSc'),
('Florida Fixed Income Group', 'Florida Fixed Income Group is established for the purpose of analyzing fixed income securities and markets, writing trade reports, and providing hands-on experience to members in writing and research via online publication.', ARRAY['Finance'], 'https://www.ffiguf.com/', NULL, 'https://media.licdn.com/dms/image/v2/D560BAQHHxR0HYp5pVw/company-logo_200_200/company-logo_200_200/0/1724644783963/ffiguf_logo?e=1764806400&v=beta&t=V04Q8ePeFY8tE4McdP2mTYWvQ9O3L19QgKP-g2_463g'),
('Florida Students of Accounting Council', 'The Florida Student of Accounting Council (FSOAC) is part of the campus-wide Board of College Councils. The Council serves as a liaison between accounting students and faculty. It sponsors professional and social programs for the benefit of its members and participates in projects that serve our community. Members have the opportunity to attend various events to meet other students interested in the field of accounting.', ARRAY['Accounting', 'Professional Development'], 'https://www.instagram.com/uf_fsoac/', NULL, 'https://media.licdn.com/dms/image/v2/C560BAQFQ3j8Tb0MAHQ/company-logo_200_200/company-logo_200_200/0/1674484954534?e=1764806400&v=beta&t=fP_8dA6QvMR-dVPmg_WuVOqqi5RWAHMQOrGgxyfCbhY'),
('Florida Technology Pathways', 'The purpose of the Florida Technology Pathways organization is to assist students to enter careers in the technology industry. We will have an 8-week bootcamp style program preparing students for the rigorous recruitment process for internships and full-time roles within the technology industry.', ARRAY['Program', 'Technology', 'Professional Development'], 'https://linktr.ee/fltechpathways?fbclid=PAZXh0bgNhZW0CMTEAAafhZZnIw3gXWj2iDdajfHe_zBTZ7AOc2D3IZtqnZonqB6rQuuZ5ez-FH-PZ0A_aem_xZUk6JEJ8CCGQeRb1W0BmQ', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQGIuZzjyH7aYw/company-logo_200_200/B4EZjZaY8ZGoAI-/0/1755994230841/florida_tech_pathways_logo?e=1764806400&v=beta&t=wyK0nhpUtjrOxBDn3QqAnOIrvfI-SFgCxLi-fBq8RX0'),
('Florida Women in Business', 'Florida Women in Business is a professional development organization that gives women the tools to succeed and break down barriers in college and beyond. Our vision is to empower women in a supportive environment and provide each member a unique experience. For example, our Mentor/Mentee program offers you a one-on-one relationship with a veteran FWIB member whose goal is to help you find your passion and be an advocate for your success. We also offer various committees that help you develop your strengths. Finally, we have inspiring speakers from prominent companies and the community who will offer their personal experiences and advice. When you join Florida Women in Business, you know you''re joining a family of dynamic women who will help you in all of your endeavors and will cheer you on every step of the way.', ARRAY['General Business', 'Women', 'Diversity', 'Professional Development'], 'http://www.fwibuf.com/', NULL, 'https://media.licdn.com/dms/image/v2/C4D0BAQFOlbhRImnGvg/company-logo_200_200/company-logo_200_200/0/1631361088914/uf_fwib_logo?e=1764806400&v=beta&t=yAnMM-LuqbMUasiqg32gKMdAPkq4pLT4ntkmKkKzUeA'),
('Future Business Leaders of America', NULL, ARRAY['General Business'], 'https://linktr.ee/uf.fbla', NULL, 'https://www.fbla.org/media/2022/08/FBLA_HorizontalLogo-600x464-1-1.png'),
('Gator Business Book Club', 'The purpose of the Gator Business Book Club is to unite a group of like-minded individuals through a common interest in finance, investing, negotiation, and productivity. The club''s mission is to help students to produce remarkable results and thrive academically and in life. The organization aims to find the best books on finance and productivity and synthesize them in quick, engaging, and actionable meetings.', ARRAY['General Business'], 'l.instagram.com/?u=http%3A%2F%2Flinktr.ee%2Fgbbc_uf%3Ffbclid%3DPAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnLEN6_kkwGF2TKfKYq_tYijJ2Lty6yuRJAI0FljYaeE__C4SOdDylL--bGBY_aem_cCAerUTebUfY5tQHIiAJMA&e=AT0s0P0k1yAqTPGy71GDkHzI3ssChBi7X_ZNWO0beEpngnYFvKPyQNW_eBp0rFd-1TZ7z5hodBTU8RSJb6SAa48ajC7jvz0hqgXp8bDIAg', NULL, 'https://ugc.production.linktr.ee/abd0743d-bc48-49df-97b6-69ed314157e8_304907269-3374377152885733-8830064741545980332-n.jpeg?io=true&size=avatar-v3_0'),
('Gatortech', 'GatorTech strives to create a community passionate about technology and its impact on the world. We are a place for anyone to gain practical exposure to popular and emerging tech and develop their core professional competencies along the way.', ARRAY['Technology', 'Professional Development'], 'https://www.instagram.com/gatortechuf/?hl=en', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQHXazJrunmtbA/company-logo_200_200/company-logo_200_200/0/1716301499623/gatortech_logo?e=1764806400&v=beta&t=-XDd34Vr-VKtR7Ta9U6p3sr3SZiDQ9Qzula7Tsj6B5M'),
('Gator Hatchery', 'UF''s student business accelerator, incubator, and dreammaker', ARRAY['Entrepreneurship'], 'https://warrington.ufl.edu/current-students/gator-hatchery/', NULL, NULL),
('Gator Student Consulting Organization', 'UF''s premier consulting organization', ARRAY['Consulting', 'Professional Development'], 'https://lnk.bio/uf-gsco?fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnwALUY9Uc5LL0QdRIeTs_yV2mqWKrRWQUpOlwjIAEPvg8_8Lz24BwRFhFNUc_aem_a2q_h37n_CIzBhq22QuU0g', 'GSCO@groups.mail.ufl.edu', 'https://cdn2.lnk.bi/profilepics/-1625679_20250828345.png'),
('Gator Student Investment Fund', 'Gator Student Investment Fund (GSIF) is a student-run, long-only equity fund that manages ~$1,200,000 of capital on behalf of the University of Florida endowment. ', ARRAY['Investment Funds', 'Finance'], 'https://warrington.ufl.edu/gator-student-investment-fund/', NULL, 'https://media.licdn.com/dms/image/v2/D560BAQFrLrVarWTWyA/company-logo_200_200/company-logo_200_200/0/1702398894877/gatorstudentinvestmentfun_logo?e=1764806400&v=beta&t=InH9k_rGDIyvofXwvCeg0YQv51Bu07fNafLm3D1859E'),
('Gator SLAM', 'GatorSLAM, or Sales Leadership and Mentorship, is an experiential learning activity for sales students at the Warrington College of Business. GatorSLAM teaches the art of salesmanship to young leaders like you, while instilling the soft skills you''ll need in both your professional and personal life. With you in the driver''s seat we''ll tackle topics relevant to you. From time management, to building confidence through leadership, how to land that internship, and finally, first job in the field.', ARRAY['Marketing', 'Professional Development'], 'http://warrington.ufl.edu/current-students/undergraduate/gator-slam/', NULL, NULL),
('Global Business Brigades', 'Global Business Brigades at the University of Florida is a nonprofit, student-led movement to promote financial literacy and stability in the developing world.', ARRAY['International Business'], 'http://instagram.com/gbb_uf', NULL, 'https://media.licdn.com/dms/image/v2/C560BAQEz_GuK93IMGA/company-logo_200_200/company-logo_200_200/0/1630643986177/global_business_brigades_at_uf_logo?e=1764806400&v=beta&t=BcRrg5hjnLFU4xGv_fAO-ztXwii0YM7f317vsXeGzmw'),
('Heavener Internatioal Case Competition', 'The Heavener International Case Competition (HICC) is a global undergraduate business case competition held at the University of Florida.', ARRAY['General Business'], 'https://warrington.ufl.edu/current-students/undergraduate/international-case-competition/', NULL, NULL),
('Hedging & Trading Collective', 'Preparing students for careers in sales & trading and asset management through practical portfolio management.', ARRAY['Finance', 'Professional Development'], 'https://www.instagram.com/accounts/login/?next=https%3A%2F%2Fwww.instagram.com%2Fhtc_uf%2F&is_from_rle', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQF_uvwxVkN0LQ/company-logo_200_200/company-logo_200_200/0/1708043776520/uf_hedging_trading_collective_logo?e=1764806400&v=beta&t=7ogYMPLQDsvMWD9Mme7Dr5EEl6aR2ali67ITEbVVprQ'),
('Hispanic Finance Association', 'The Hispanic Finance Association is an organization that helps undergraduate students receive competitive job offers. We hope to increase Hispanic representation in the financial services industry through education and one-on-one mentorship, empowering the next generation of leaders. We are one chapter of over 25 across the globe.', ARRAY['Finance', 'Diversity', 'Professional Development'], 'https://hfaflorida.wixsite.com/website', 'floridahfa@gmail.com', 'https://media.licdn.com/dms/image/v2/C560BAQH_l3sCwN3u1Q/company-logo_200_200/company-logo_200_200/0/1674485155000/florida_hispanic_finance_association_logo?e=1764806400&v=beta&t=4Q11g8Vy75i7N499Y4Cx322FUO99Bn5h_zg9s3mNlNw'),
('Latin American Women in Business', 'Dedicated to the professional development, relationship building, and personal growth of Latin American Women at UF.', ARRAY['General Business', 'Women', 'Diversity', 'Professional Development'], 'https://lawibuf.wixsite.com/lawib', NULL, 'https://media.licdn.com/dms/image/v2/D560BAQFPJ4fvK4N4lg/company-logo_200_200/company-logo_200_200/0/1682439782941/latin_american_women_in_business_uf_logo?e=1764806400&v=beta&t=DJMnyyXVlxip6YnnlFBfvrNz2UrjfsHjC_NWGLu5O8I'),
('NABA', 'An organization at The University of Florida that provides its members a platform to enhance skills and elevate voices.', ARRAY['Accounting', 'Diversity'], 'https://sites.google.com/view/nabagator', NULL, 'https://media.licdn.com/dms/image/v2/C560BAQHditIXA_cQeQ/company-logo_200_200/company-logo_200_200/0/1679708643902/nabauf_logo?e=1764806400&v=beta&t=CJnq6sUimdHXe9FbrujroD-iAlOm7OXzxDW64_msDZo'),
('JBiz', 'For aspiring Jewish business students who want to build their professional network.', ARRAY['General Business', 'Diversity'], 'https://jbizuf.netlify.app/?fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnFK6-tjrdLWYiNj-HYFllXvo7WPLw_aPTXtX250uP0I8WNHSYpOOT2kNFeZQ_aem_cSb1OzmfqVqtYpQ5l8LwMg', NULL, NULL),
('Personal Finance Club', 'UF Personal Finance''s mission is to improve financial literacy among students in the Gainesville community, and create an engaging experience while doing so. Our goal is for our members to start diving into their financial objectives from a young age!', ARRAY['Finance'], 'https://linktr.ee/pfcuf?utm_source=linktree_profile_share&ltsid=21b86989-a28b-4a3e-a2cd-4464f47b5719&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnYVdIODcALVFCS5SwK6Wg9n7NZqH-7FClkyWfE3GP71O8T9KYdSYCOW6FLGk_aem_S0MsvrarFGYL0GL7mpY3OA', NULL, 'https://ugc.production.linktr.ee/1d8104dc-6c51-4d91-b972-a6bf0aa52ee6_PFC-Logo.png?io=true&size=avatar-v3_0'),
('Pi Sigma Epsilon', 'Sales, Marketing, and Management Fraternity at the University of Florida.', ARRAY['General Business', 'Marketing', 'Professional Development', 'Fraternity'], 'https://pseflorida.com/', NULL, 'https://media.licdn.com/dms/image/v2/C4D0BAQEDsHY857hdew/company-logo_200_200/company-logo_200_200/0/1630516953659?e=1764806400&v=beta&t=CVyrXNw3WRA-QtJxNii0syVrLjzlBNSEKnS9LVU46KI'),
('Pride in Business', 'A club for queer UF students of all majors to network with one another and grow professionally', ARRAY['General Business', 'Diversity'], 'https://linktr.ee/uflpib?fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnJhqu0xutmirjZ3c4K1jVj_PKo7-ZcHS5LnE8UaAPnSwdozfgG10WH-2ycm4_aem_xGPyc9i9I4N9CV1C7uWvng', 'uflpib@gmail.com', 'https://ugc.production.linktr.ee/0TC0OQF8RSOOCib177y7_VbfY367tfVjik7hM?io=true&size=avatar-v3_0'),
('Product Space', 'A nation-wide family of students who are passionate about becoming product leaders.', ARRAY['Technology', 'Professional Development'], 'https://linktr.ee/ufproductspace?fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGn7USOW-ROz2vbovf_kMooD7whoMXS9KXacBLdVu-7F3kNf_3q0wSi8w2Mz14_aem_qz8kUFCB-hLJjuFkQGSMSw', NULL, 'https://ugc.production.linktr.ee/jkNR5Af5SAinCFBNP1Fw_Gk4an1h8yEC51o7i?io=true&size=avatar-v3_0'),
('Real Estate Society', 'Education, Growth, Meaningful Relationships, and Professional Development in Real Estate at UF.', ARRAY['Real Estate', 'Professional Development'], 'https://warrington.ufl.edu/current-students/real-estate-society/', 'ufressociety@gmail.com', 'https://media.licdn.com/dms/image/v2/C560BAQGOpyZIhn6n4g/company-logo_200_200/company-logo_200_200/0/1630650854890/uf_real_estate_society_logo?e=1764806400&v=beta&t=kphgZoCJpkEOJxKVpz3XbWlRCZaUtcWkYo4C0Grgi9A'),
('Rem on Campus', 'The purpose of Rem on Campus is to create an immersive curriculum shaping students and young problem-solvers into the next generation of impact-driven innovators. Rem on Campus is a way for students to develop new personal and professional relationships, engage in unique hands-on learning experiences, and most of all, positively impact their community.', ARRAY['General Business'], 'https://www.instagram.com/remoncampus/?hl=en', NULL, NULL),
('Retail Society', 'Student organization connecting students with the retail industry and professionals with bi-weekly meetings', ARRAY['General Business'], 'https://linktr.ee/retailinggators?fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGn0jWzuUKFjRQL0kWIR17RNu0oubObooHFCXe3w9GPY8ap4gxeNGwWUnhUyLE_aem_n_EzL0cCQkeAYr-E-NsDxg', NULL, 'https://ugc.production.linktr.ee/2cffb3eb-2e7a-44cb-a72e-121af382dff1_UF-Retail-Society-Logo.png?io=true&size=avatar-v3_0'),
('Sales in the Swamp', 'In Sales in the Swamp, you''ll demonstrate your ability to sell a product or service to a consumer in a role-play competition. Facilitated by the Warrington College of Business Professional Selling program, the competition offers you an exciting opportunity to hone your selling skills. ', ARRAY['Marketing'], 'https://warrington.ufl.edu/current-students/sales-in-the-swamp/', NULL, NULL),
('Student Finance Group', 'Connecting and Empowering UF''s Brightest Business Students', ARRAY['Finance', 'Professional Development'], 'https://www.ufsfg.com/', NULL, 'https://media.licdn.com/dms/image/v2/C4E0BAQEV2uEi19s_Iw/company-logo_200_200/company-logo_200_200/0/1630641037881?e=1764806400&v=beta&t=wFZj2GzVmJXq6IN2F4VdR2Ku1iQ8J1nEMZrag77PeSw'),
('Student Investment Club', 'The Student Investment Club at the University of Florida is the best place to learn all about your money. We make investing simple, with applicable skills taught each week for novices and experts alike.  Connect with us to stay informed about our upcoming meetings and events. Meet us in Stuzin 103 every Tuesday night at 6:30! All majors and experience levels are welcome!', ARRAY['Finance'], 'https://ufsiclinktree.my.canva.site/?fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnsVxSRW2sZJInG6pYPp6HyQ9Q4eFmG4e7y9QSCWDzHs9PpIDW23-vXgTtA40_aem_Ugtrnvfxf6Vbh-x1evR5eg', NULL, 'https://static.wixstatic.com/media/18f6b9_976966566d1c4202a6dd51f2d290e2e7~mv2.png/v1/fill/w_224,h_224,al_c,lg_1,q_85,enc_avif,quality_auto/18f6b9_976966566d1c4202a6dd51f2d290e2e7~mv2.png'),
('Student Money Skills Club', 'Our purpose is to aid members in developing the basic personal financial skills needed to be successful in life.', ARRAY['Finance', 'Professional Development'], 'https://www.instagram.com/sms_uf/', NULL, 'https://media.licdn.com/dms/image/v2/D560BAQFhI3Bfyq3q6A/company-logo_200_200/company-logo_200_200/0/1698925032953?e=1764806400&v=beta&t=WQhP3AiSX9AKsvNwHlpE5vig5FDPbbPvfj0Ii41yJC4'),
('TAMID Group', 'TAMID provides students with hands-on investment and consulting experience within the Israeli startup ecosystem.', ARRAY['Consulting'], 'https://www.instagram.com/tamidatflorida/?hl=en', NULL, 'https://media.licdn.com/dms/image/v2/D4D0BAQEwCA0SNyXMAA/company-logo_200_200/company-logo_200_200/0/1738697676392/tamidatflorida_logo?e=1764806400&v=beta&t=C8X512huAYxcQ2kPkRG7PxW_cv4QPTYQVyGKZQ8xTxI'),
('The Founders Fund', 'The Founders Fund is a student-managed finance organization at the University of Florida that fosters financial expertise and professional growth.', ARRAY['Investment Funds', 'Finance'], 'https://www.thefoundersfunduf.com/', 'thefoundersfunduf@gmail.com', 'https://media.licdn.com/dms/image/v2/D4E0BAQEn8rkjvXYxGQ/company-logo_200_200/B4EZUMRdjcHcAI-/0/1739667659236/thefoundersfund_logo?e=1764806400&v=beta&t=R-9BM6sZYcoxhUru3rUdKLJdij0dWpTH_gYFrvlTd7M'),
('University Economics Society', 'UF Student Organization for sharing economics opportunities, connecting students and alumni, and discussion of economics', ARRAY['Economics'], 'https://linktr.ee/UFUES?fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnmHNlBAsJMN4X0c-JJuaIhiZ8ohHmYakDK1J_lTe9mEKFbr2Ck3txeCUQZeE_aem_eS2ezuO3ORUoOu5NBymkSQ', NULL, 'https://media.licdn.com/dms/image/v2/D4D0BAQGhCKTUffQ4qA/company-logo_200_200/company-logo_200_200/0/1724270220784/uf_ues_logo?e=1764806400&v=beta&t=e0MszKXyFJU26MYQSD-zmBJmiP_sVZ8w9ixt9n8NmS0'),
('Women''s Real Estate Society', 'The Women''s Real Estate Society is a professional development organization that seeks to foster a strong community of women seeking a career in commercial real estate through engaging with industry professionals via informational panels, presentations, and other networking events.', ARRAY['Real Estate', 'Women', 'Diversity', 'Professional Development'], 'https://l.instagram.com/?u=https%3A%2F%2Flinktr.ee%2FUFWRES%3Ffbclid%3DPAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnGmtnFQNfui4FJBnEUhoA3tOHSM8_fZkuDou7i8iPeWybxWdHi0AzgPmqrd8_aem_OQ7H80Y_mxQBilO5sA3V7Q&e=AT1zSR471CeOcmKFx4Vs9rWES0zgyZ0vsX7DK7AgMw82Dm57TVv399inlGT-OYGtAp5Kr5XWLBE4liS3WTVst9U0wsShNog-3k8Kdpsffg', NULL, 'https://media.licdn.com/dms/image/v2/D4E0BAQGnDc0_m_WPVw/company-logo_200_200/company-logo_200_200/0/1698164143694?e=1764806400&v=beta&t=_L_HVVyJpTUmRfqE8B395KmAxqXs1kZSEzyj89OkF88')
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  website = EXCLUDED.website,
  email = EXCLUDED.email,
  image = EXCLUDED.image;

-- Verify the import
-- SELECT COUNT(*) FROM organizations;
-- Should return 52

